\input texinfo    @c -*-texinfo-*-
@c %**start of header
@setfilename binitools.info
@include version.texi
@settitle The binitools and BINI Format Guide
@c %**end of header

@copying
This manual for for binitools, version @value{VERSION}, as well as
information about the BINI format.

Copyright @copyright{} 2007 Christopher Wellons
<@email{ccw129@@psu.edu}>.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,''
and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License.''

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end quotation
@end copying

@titlepage
@title The binitools and BINI Format Guide
@subtitle for binitools version @value{VERSION}, @value{UPDATED}
@author Christopher Wellons (@email{ccw129@@psu.edu})

@page
@vskip 0pt plus 1filll
@insertcopying

@end titlepage

@contents

@ifnottex
@node Top
@top binitools

@insertcopying
@end ifnottex

@menu
* Preface::          An introduction
* Using unbini::     Unpacking BINI files.
* Using bini::       Repcking BINI files.
* Tips and Tricks::  Useful binitools tricks.
* The BINI Format::  Detailed information on the BINI format.
* Index::            Complete index.
@end menu

@c Preface
@node Preface
@chapter Preface
@cindex preface

@c The unbini usage chapter.
@node Using unbini
@chapter Using unbini
@cindex unbini

@c The bini usage chapter.
@node Using bini
@chapter Using bini
@cindex bini

@c Tips and Tricks
@node Tips and Tricks
@chapter Tips and Tricks
@cindex tricks
@cindex tips

@c The BINI Format
@node The BINI Format
@chapter The BINI Format
@cindex format

@c End the manual with the index.
@node Index
@unnumbered Index

@printindex cp   

@bye
